"""Writes src/nozzles_gen.h, the exhausts of the stock models the plugin's jets fly as they are (src/exhaust_nozzles.h
includes it): the bombers an airstrike's strike jet takes over and the gunship (pylib/jet_models.py STOCK_BOMBERS). The
plugin's own models carry their nozzles as bones (jet_models.with_nozzles); these are the game's, which cannot, so their
exits are measured the same way (jet_models.exit_nozzles: NOZZLE_EXITS's rim vertices, the flame as big as the engine) on
the models in Root.cpk (read only) and written here, each nozzle's local matrix on the bone it hangs on (in that bone's
bind frame: its bind need not be the identity) and its flame's length and width. A model is known by a bone of its own
name and its bone count (the plugin's multirole model has a `bomber401` bone too, and more bones).

  python tools/gen_nozzles.py            write it (needs Root.cpk)
  python tools/gen_nozzles.py --check    exit 1 when the committed file is not what this would write (CI). Without
                                         Root.cpk (CI): the file's own record of what it was made from (its `data` line)
                                         is checked against today's inputs (NOZZLE_EXITS, FLAME_LENGTH_PER_DIAMETER, this
                                         generator's version) and the file re-rendered from it must be the file; the
                                         models themselves are only re-measured where the game is.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'pylib'))
import jet_models  # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'nozzles_gen.h'))
VERSION = 1   # this generator's: bump when what it measures or how it writes changes
DATA = '// data: '


def inputs() -> dict:
    """What the file is made from, besides the game's models: the generator's version, the flame's proportion, each stock
    model's exit box."""
    return {'version': VERSION, 'flame_length_per_diameter': jet_models.FLAME_LENGTH_PER_DIAMETER,
            'exits': {name: jet_models.NOZZLE_EXITS[name] for name in jet_models.STOCK_BOMBERS}}


def measure(game) -> dict:  # noqa: ANN001 - rootcpk.Game
    """{'inputs': inputs(), 'models': {name: its bone count, the bone the nozzles hang on, each nozzle's local matrix
    (on that bone, rounded to 1e-6) and flame (length, width), its .mdb's sha256}} for every stock bomber."""
    from mdb import bind_world, inverse_affine, mmul, rab_read
    models = {}
    for name, (arc, mdl) in jet_models.STOCK_BOMBERS.items():
        data = next(f for f in rab_read(game.read('OBJECT', arc)).files if f.name.lower() == mdl).data
        md = jet_models._model_of(game, name)
        assert md.bone_index(name) >= 0, f'{name}: no bone of its name to know it by'
        w = bind_world(md)
        nozzles = jet_models.exit_nozzles(md, name)
        parents = {n.parent for n in nozzles}
        assert len(parents) == 1, f'{name}: nozzles on {parents}'
        parent = parents.pop()
        inv = inverse_affine(w[md.bone_index(parent)])
        models[name] = {'bones': len(md.bones), 'parent': parent, 'sha256': hashlib.sha256(data).hexdigest(),
                        'local': [[round(x, 6) + 0.0 for x in mmul(list(n.bind), inv)] for n in nozzles],
                        'flame': [[n.length, n.width] for n in nozzles]}
    return {'inputs': inputs(), 'models': models}


def _f(x: float) -> str:
    """A float literal (6 significant digits; always with a point: `1f` is no C++ literal)."""
    s = f'{x:.6g}'
    return (s if '.' in s or 'e' in s else s + '.0') + 'f'


def render(data: dict) -> str:
    lines = ['// Generated by tools/gen_nozzles.py from the stock models in Root.cpk (pylib/jet_models.py STOCK_BOMBERS,',
             '// NOZZLE_EXITS, exit_nozzles). Do not edit: python tools/gen_nozzles.py (with the game) rewrites it.',
             DATA + json.dumps(data, sort_keys=True, separators=(',', ':')),
             '#pragma once',
             '',
             'namespace crew::exhaust {',
             '// {the model\'s own bone, its bone count, the bone the nozzles hang on, how many, each one\'s local matrix on it,',
             '//  each one\'s flame (length, width)}',
             'inline constexpr StockNozzles kStockNozzles[]={']
    for name, m in data['models'].items():
        local = ','.join('{' + ','.join(_f(x) for x in row) + '}' for row in m['local'])
        flame = ','.join('{' + ','.join(_f(x) for x in f) + '}' for f in m['flame'])
        lines.append(f'    {{L"{name}",{m["bones"]},L"{m["parent"]}",{len(m["local"])},{{{local}}},{{{flame}}}}},')
    lines += ['};', '}  // namespace crew::exhaust']
    return '\n'.join(lines) + '\n'


def _committed() -> str:
    with open(OUT, encoding='utf-8', newline='') as f:
        return f.read().replace('\r\n', '\n')


def check(game=None) -> str | None:  # noqa: ANN001 - rootcpk.Game
    """None when the committed file is current, else why not (see the module doc: with `game` re-measured, else checked
    against its own record)."""
    text = _committed()
    if game is not None:
        return None if text == render(measure(game)) else 'the stock models measure otherwise'
    line = next((x for x in text.split('\n') if x.startswith(DATA)), None)
    if line is None:
        return f'no {DATA.strip()} line'
    data = json.loads(line[len(DATA):])
    if json.loads(json.dumps(inputs())) != data['inputs']:
        return f'made from {data["inputs"]}, the inputs are now {inputs()}'
    return None if render(data) == text else 'its tables are not what its data line renders'


def main(argv: list[str]) -> int:
    from rootcpk import DEFAULT_GAME, Game
    have = os.path.isfile(os.path.join(DEFAULT_GAME, 'Root.cpk'))
    if '--check' in argv:
        why = check(Game(DEFAULT_GAME) if have else None)
        print(f'{os.path.relpath(OUT)}: {"current" if why is None else "STALE: " + why} '
              f'({"re-measured on the game" if have else "no Root.cpk: checked against its own record"})')
        return 0 if why is None else 1
    if not have:
        print('needs the game (Root.cpk) to measure the stock models', file=sys.stderr)
        return 2
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(render(measure(Game(DEFAULT_GAME))))
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
