"""Writes src/calls.inc, the plugin's side of the call weapons (src/airstrike.cpp includes it), from tools/calls.py:
  kCalls       the calls the plugin flies (Call), in CALLS order (the in-mission pick cycles through them)
  kCallLabels  their names on the pick's banner (the SC names the weapons carry)
  kCallRows    every row tools/call_weapons.py installs (vehicle requests too): its id, its weapon SGO under
               Mods/WEAPON and the object SGO a vehicle request brings under Mods/OBJECT (nullptr: none)
  kThrows      the thrown drones (Robot Bombs, brings 'throw'): the marker's float bits, the drone, its fuel

  python tools/gen_calls.py            write it
  python tools/gen_calls.py --check    exit 1 when the committed file is not what this would write (CI)
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import calls  # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, '..', 'src', 'calls.inc'))
BRINGS = {'jets': 'Brings::jets', 'helis': 'Brings::helis', 'sub': 'Brings::sub'}


def _wstr(s: str) -> str:
    return 'L"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _float(x: float) -> str:
    return f'{float(x):.1f}f'


def _opt(enum: str, value: str) -> str:
    return f'{enum}::{value}' if value else 'std::nullopt'


def _call(c: calls.Call) -> str:
    return (f'    {{{_float(c.mark)},{BRINGS[c.brings]},{_opt("JetRole", c.role)},{_opt("HeliBody", c.body)},'
            f'{c.count},{c.fuel_sec},{"true" if c.follow else "false"},"{c.log}",{_wstr(c.id)}}},')


def _throw(c: calls.Call) -> str:
    return f'    {{0x{calls.mark_bits(c):08X}u,ThrownDrone::{c.drone},{c.fuel_sec},"{c.log}",{_wstr(c.id)}}},'


def _row(c: calls.Call) -> str:
    weapon = _wstr(f'{c.id.upper()}.SGO')
    obj = _wstr(f'{c.vehicle.upper()}.SGO') if c.vehicle else 'nullptr'
    return f'    {{{_wstr(c.id)},{weapon},{obj}}},'


def render() -> str:
    lines = [
        '// Generated by tools/gen_calls.py from tools/calls.py: do not edit (CI checks it is current).',
        '// Included by src/airstrike.cpp after its Brings / Call / CallRow definitions.',
        '',
        '// The calls the plugin flies, in tools/calls.py CALLS order.',
        'const Call kCalls[]={',
        *[_call(c) for c in calls.FLOWN],
        '};',
        'constexpr int kCallCount=static_cast<int>(sizeof(kCalls)/sizeof(kCalls[0]));',
        '// kCalls\' names on the in-mission pick\'s banner (the SC names the weapons carry).',
        'const wchar_t* const kCallLabels[]={',
        *[f'    {_wstr(calls.call_name(c, "SC"))},' for c in calls.FLOWN],
        '};',
        'static_assert(sizeof(kCallLabels)/sizeof(kCallLabels[0])==kCallCount,"a label per call");',
        '// Every weapon table row tools/call_weapons.py installs, vehicle requests too, in table order of a',
        '// fresh install.',
        'const CallRow kCallRows[]={',
        *[_row(c) for c in calls.CALLS],
        '};',
        'constexpr int kCallRowCount=static_cast<int>(sizeof(kCallRows)/sizeof(kCallRows[0]));',
        '// The thrown drones: their weapons\' AmmoHitSizeAdjust bits (weapon +0x8C4), in tools/calls.py CALLS order.',
        'const Throw kThrows[]={',
        *[_throw(c) for c in calls.CALLS if c.brings == 'throw'],
        '};',
        '',
    ]
    return '\n'.join(lines)


def main(argv: list[str]) -> int:
    text = render()
    current = None
    if os.path.isfile(OUT):
        with open(OUT, encoding='utf-8', newline='') as f:
            current = f.read().replace('\r\n', '\n')
    if '--check' in argv:
        if current != text:
            print(f'{OUT} is stale: run python tools/gen_calls.py and commit it')
            return 1
        print(f'{OUT} is current')
        return 0
    if current != text:
        with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'wrote {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
