"""Readable digests of the stock mission scripts, for discussing changes on the test site (testhub, level plan).

  python -B tools/make_mission_digest.py [GAME_DIR] [--out DIR] [--only KEY ...]

Made on this machine from the player's own Root.cpk and uploaded to the logged-in site with
`python tools/testhub.py digests DIR`; never committed (the repository is public and the scripts are the game's).

EDF6 missions (MISSION/EDF6/<id>/MISSION.AC, AngelScript generated by the developers' event editor): one block per
event, in event order: its name, what it does (the script with the editor's scaffolding, loading, lighting and
commented-out code taken out), the lines it speaks (voice ids replaced by speaker and Simplified Chinese caption
from MISSION/EDF6_VOICETABLE*.SGO), and the events it starts with their conditions (well-known Factor_* calls
put in words, the call kept beside them; the others as written).

EDF5 missions (MISSION/EDF5_OLD_SCRIPT/<id>/MISSION.BVM, compiled): no event structure survives, so only what the
string pool shows: maps, objects, music, and the voice lines in string-pool order (not necessarily play order).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'pylib'))
sys.path.insert(0, HERE)
import dsgo  # noqa: E402
import make_edf5_campaign as edf5  # noqa: E402
import rootcpk  # noqa: E402

MISSIONS = os.path.join(HERE, '..', 'testhub', 'src', 'missions.json')
OUT = os.path.join(HERE, '..', 'tmp', 'digests')

# ------------------------------------------------------------------ voices

Voices = dict[str, tuple[str, str]]


def voices(game: rootcpk.Game) -> Voices:
    """Voice id -> (speaker, SC caption): the id table names each row index, the language table holds the row."""
    ids = dsgo.parse(game.read('MISSION', 'EDF6_VOICETABLE.SGO')).root.items[0]
    rows = dsgo.parse(game.read('MISSION', 'EDF6_VOICETABLE.SC.SGO')).root.items[0].items
    out: Voices = {}
    for i, vid in ids.names.items():
        if i < len(rows) and isinstance(rows[i], dsgo.Node) and len(rows[i].items) >= 2:
            out[vid] = (str(rows[i].items[0]), str(rows[i].items[1]).replace('\n', ' '))
    return out


def say(vid: str, table: Voices) -> str:
    who, text = table[vid]
    return f'{who}：「{text}」'


# ------------------------------------------------------------------ EDF6 scripts

TEAMS = {'TEAM_ID_ENEMY': '敌方', 'TEAM_ID_FRIEND': '友方', 'TEAM_ID_PLAYER': '玩家方'}
LEVELS = {'MISSION_DIFFICULTY_EASY': '简单', 'MISSION_DIFFICULTY_NORMAL': '普通', 'MISSION_DIFFICULTY_HARD': '困难',
          'MISSION_DIFFICULTY_HARDEST': '极难', 'MISSION_DIFFICULTY_INFERNO': '炼狱'}


def _args(text: str) -> list[str]:
    """Top-level arguments of a call's text 'Name(a, f(b, c), "d,e")' (comments already removed)."""
    inner = text[text.index('(') + 1:text.rindex(')')]
    out, depth, cur, quote = [], 0, '', False
    for ch in inner:
        if ch == '"':
            quote = not quote
        if not quote and ch in '([{':
            depth += 1
        if not quote and ch in ')]}':
            depth -= 1
        if ch == ',' and depth == 0 and not quote:
            out.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def _plain(a: str) -> str:
    a = a.strip().strip('"')
    return TEAMS.get(a, LEVELS.get(a, a))


# Factor_* calls whose meaning is plain from the name and the editor's own argument labels.
FACTORS = {
    'Factor_Wait': lambda a: f'等 {a[0]} 秒',
    'Factor_PlayerAreaIn': lambda a: f'玩家进入区域「{_plain(a[0])}」',
    'Factor_TeamEncount': lambda a: f'{_plain(a[0])}进入交战',
    'Factor_TeamNotEncount': lambda a: f'{_plain(a[0])}不在交战',
    'Factor_TeamObjectCount': lambda a: f'{_plain(a[0])}存活数 ≤ {a[1]}',
    'Factor_TeamBigObjectCount': lambda a: f'{_plain(a[0])}大型目标存活数 ≤ {a[1]}',
    'Factor_GroupObjectCount': lambda a: f'{a[0]} 组存活数 ≤ {a[1]}',
    'Factor_AiMoveEnd': lambda a: f'{a[0]} 走完路线',
    'Factor_AiMoveEndOrDie': lambda a: f'{a[0]} 走完路线或阵亡',
    'Factor_ObjectDestroy': lambda a: f'{a[0]} 被摧毁',
    'Factor_PlayerObjectDistance': lambda a: f'玩家离 {a[0]} ≤ {a[1]} 米',
    'Factor_FlagOn': lambda a: f'标志 {a[0]} 打开',
    'Factor_FlagOff': lambda a: f'标志 {a[0]} 关闭',
    'Factor_DifficultyOverEqu': lambda a: f'难度 ≥ {_plain(a[0])}',
    'Factor_DifficultyLessEqu': lambda a: f'难度 ≤ {_plain(a[0])}',
    'Factor_RideVehicle': lambda a: '玩家上了载具' if not a else f'上了载具 {", ".join(a)}',
    'Factor_IsOnlineMode': lambda a: '联机时',
    'Factor_IsRetry': lambda a: '重试时',
    'Factor_IsNotRetry': lambda a: '不是重试时',
}

# Statements that are the event editor's scaffolding or loading/lighting detail, not the mission's content.
NOISE = re.compile(r'^(::|internal_|__|IsBoolState|Mutex_|WaitVoice\(\)|g_soldiers\s*=\s*GetTalkers|Preload|WaitPreload|'
                   r'BeginLoading|EndLoading|Online_WaitStart|EventLightTool\b|tool\.|const uint32 MAX_EVENT_ID|'
                   r'return;$|\w+_usercode\(\);|if\(\s*::)')
# Dropped ideas (code switched off, debug-only placeholder text, superseded dialogue, events nothing starts) are
# kept but marked: a digest line starting with DEAD is shown greyed on the site.
DEAD = '⊘ '
DEAD_COMMENT = '//⊘ '
DEBUG_TEXT = re.compile(r'^DebugMessageW\(\s*"([^"]*)"')
# Presentation only (animation, facing, camera, chatter switches): left out of the digest.
SHOW = re.compile(r'(^|\.)(AppealAnimation\w*|SetAiObjectDirection_\w+|ClearAiObjectDirection|LookCameraTo\w+|CloseUi|'
                  r'SetCharacterRandomTalk|EnableAiRandomTalk|DisableAiRandomTalk|TalkBegin|TalkEnd|EnvFadeAnimation)\s*\(')
# A // comment that is code switched off rather than a note.
CODE_COMMENT = re.compile(r'^//\s*([\w.:\[\]]+\s*(\(|=[^=])|.*;\s*(//.*)?$)')
SPEECH = re.compile(r'^(Speak_\w+|RadioVoice|Talk_\w+)\s*\(')
NUM_F = re.compile(r'\b(\d+(?:\.\d+)?)f\b')
DROP_COMMENTS = re.compile(r'^//\s*(\[e2d_section_data\]|ゲーム進行スクリプト|音声スクリプト|-{5,})')
EVENT = re.compile(r'internal_CreateEvent\(\s*"__([0-9A-Fa-f]{4})_game_event"\s*,\s*"([^"]*)"\s*,[^,]*,\s*(EVENT_TYPE_\w+)\s*,\s*(EVENT_CHECK_\w+)')


def mark_block_comments(text: str) -> str:
    """/* ... */ spanning lines or longer than a label is code the developers switched off: each of its lines
    becomes a `//⊘` comment (shown greyed as a dropped idea). One-line argument labels /*名*/ stay as they are."""
    def mark(m: re.Match) -> str:
        body = m.group(0)[2:-2]
        if '\n' not in body and len(body) <= 30:
            return f'/*{body.strip()}*/'
        return '\n' + '\n'.join(DEAD_COMMENT + x.strip() for x in body.split('\n') if x.strip()) + '\n'
    return re.sub(r'/\*.*?\*/', mark, text, flags=re.S)


def functions(text: str) -> dict[str, str]:
    """Top-level function bodies by name, brace matched outside // comments and strings (switched-off code in
    comments holds braces)."""
    out: dict[str, str] = {}
    for m in re.finditer(r'^void\s+(\w+)\s*\(\s*\)\s*\n\{', text, flags=re.M):
        depth, i = 1, m.end()
        while depth and i < len(text):
            c = text[i]
            if c == '/' and text.startswith('//', i):
                i = text.find('\n', i)
                i = len(text) if i < 0 else i
                continue
            if c == '"':
                i = text.find('"', i + 1) + 1 or len(text)
                continue
            depth += {'{': 1, '}': -1}.get(c, 0)
            i += 1
        out[m.group(1)] = text[m.end():i - 1]
    return out


def statements(body: str) -> list[tuple[int, str]]:
    """(indent, statement) with multi-line calls joined; a continuation line's // comment becomes /*...*/ after its
    own argument. Switched-off code (`//⊘` lines, // comments that are code, and the lines continuing such a
    call) is joined the same way and comes out as one `//⊘` statement."""
    out: list[tuple[int, str]] = []
    pending: list | None = None   # [indent, text, depth, dead]

    def flush() -> None:
        nonlocal pending
        if pending:
            out.append((pending[0], (DEAD_COMMENT if pending[3] else '') + pending[1]))
        pending = None

    for raw in body.split('\n'):
        line = raw.strip()
        if not line:
            continue
        indent = len(raw) - len(raw.lstrip('\t'))
        dead = False
        if line.startswith(DEAD_COMMENT.strip()):
            dead, line = True, line[len(DEAD_COMMENT.strip()):].strip()
        elif line.startswith('//') and (CODE_COMMENT.match(line) or (pending and pending[3])):
            dead, line = True, line[2:].strip()
        if pending and dead != pending[3]:
            flush()
        if pending:
            code, _, note = line.partition('//')
            code = code.strip()
            label = f' /*{note.strip()}*/' if note.strip() else ''
            pending[1] += ' ' + (code[:-1] + label + ',' if label and code.endswith(',') else code + label)
            pending[2] += code.count('(') - code.count(')')
            if pending[2] <= 0:
                flush()
            continue
        if not dead and line.startswith('//'):
            out.append((indent, line))
            continue
        code = line.split('//')[0]
        d = code.count('(') - code.count(')')
        if d > 0:
            pending = [indent, code.strip(), d, dead]
            continue
        out.append((indent, (DEAD_COMMENT if dead else '') + line))
    flush()
    return out


@dataclass
class Link:
    target: int
    name: str
    check: str
    conds: list[str] = field(default_factory=list)


@dataclass
class Part:
    lines: list[str] = field(default_factory=list)
    links: list[Link] = field(default_factory=list)


def factor(call: str) -> str:
    name = call.split('(')[0].split('.')[-1]
    plain = re.sub(r'/\*.*?\*/', '', call)
    try:
        args = [NUM_F.sub(r'\1', x) for x in _args(plain)]
        if name in FACTORS:
            return f'{FACTORS[name](args)}（{name}）'
    except (IndexError, ValueError):
        pass
    return NUM_F.sub(r'\1', plain.removeprefix('e.').rstrip(';').strip())


def readable(stmt: str) -> str:
    return NUM_F.sub(r'\1', re.sub(r'"app:/(?:object|Object)/([^"]+?)\.sgo"', r'\1', stmt))


def summary(text: str) -> list[str]:
    """The map and every object the live script creates or spawns, before the event walk."""
    maps = sorted(set(re.findall(r'\bMap\(\s*"app:/map/([^"]+?)\.mac"\s*,\s*"([^"]*)"', text, flags=re.I)))
    objects = sorted(set(re.findall(r'"app:/object/([^"]+?)\.sgo"', text, flags=re.I)), key=str.lower)
    return ['地图：' + ('、'.join(f'{m}（{w}）' for m, w in maps) or '（无）'),
            '出场对象：' + ('、'.join(objects) or '（无）'), '']


def part(body: str, table: Voices) -> Part:
    """An event's usercode: its own statements, then the links it registers (`{ ... CreateEvent ...; e.Factor_...; }`)."""
    out = Part()
    base = None
    link: Link | None = None
    notes: list[str] = []   # comments waiting for the statement they describe
    for indent, s in statements(body):
        if DROP_COMMENTS.match(s) or s in ('{', '}', '};'):
            continue
        dead = s[len(DEAD_COMMENT):].strip() if s.startswith(DEAD_COMMENT) else None
        if dead is not None:
            if link:   # a condition switched off
                link.conds.append(DEAD + (factor(dead) if dead.startswith('e.Factor_') else dead))
                continue
            code = dead.lstrip('{} ')
            if not code or NOISE.match(code) or SHOW.search(code) or DROP_COMMENTS.match(code):
                continue
        else:
            code = s.lstrip('{} ')
        m = EVENT.search(s) if dead is None else None
        if m:
            notes = []
            link = Link(int(m.group(1), 16), m.group(2), 'OR' if m.group(4).endswith('OR') else 'AND')
            out.links.append(link)
            continue
        if dead is None and s.startswith('e.Factor_') and link:
            link.conds.append(factor(s))
            continue
        if dead is None and link and s.startswith('//'):
            link.conds.append(s)
            continue
        if dead is None and (s.startswith('if( IsBoolState') or NOISE.match(code) or SHOW.search(code)):
            notes = []   # the notes were about what is left out
            continue
        link = None
        if base is None:
            base = indent
        pad = '  ' * max(0, indent - base)
        if dead is None and s.startswith('//'):
            notes.append(pad + s)
            continue
        out.lines += notes
        notes = []
        out.lines += statement_lines(code if dead is None else dead, pad, table, dead is not None)
    out.lines += notes
    return out


def statement_lines(s: str, pad: str, table: Voices, dead: bool) -> list[str]:
    """One kept statement: dialogue as its caption (with the superseded draft line in its trailing comment marked
    as dropped), debug-only text as dropped, anything else as written."""
    mark = DEAD if dead else ''
    debug = DEBUG_TEXT.match(s)
    if debug:
        return [DEAD + pad + '调试文字：' + debug.group(1)]
    code, _, trailing = s.partition('//')
    said = [vid for vid in re.findall(r'"([A-Z]{1,3}\d{3}_[0-9A-Z]+)"', code) if vid in table]
    head = code.split('(')[0]
    if said and SPEECH.match(head.split('.')[-1] + '('):
        out = [mark + pad + '说：' + say(vid, table) for vid in said]
        if trailing.strip():
            out.append((DEAD + pad + '旧稿：' if '「' in trailing else mark + pad + '//') + trailing.strip())
        return out
    return [mark + pad + readable(s.rstrip('{').rstrip())] + [mark + pad + '    ' + say(vid, table) for vid in said]


def digest_ac(text: str, table: Voices) -> str:
    text = mark_block_comments(text)
    names = {int(n): v for n, v in re.findall(r'internal_GetEventState\((\d+)\)\.SetName\("([^"]*)"\)', text)}
    fns = functions(text)
    # An event's links are registered in its usercode and also in its wrapper (__XXXX_game_event / Main), which
    # starts some of them as soon as the event runs.
    parts = {n: [part(fns.get(f, ''), table) for f in (
        ('Main', 'Main_usercode') if n == 0 else (f'__{n:04X}_game_event', f'__{n:04X}_game_event_usercode')
    ) + (f'__{n:04X}_voice_event_usercode',)] for n in sorted(names)}
    live = re.sub(r'^\s*//.*$', '', text, flags=re.M)
    started = {int(h, 16) for h, *_ in EVENT.findall(live)}   # anything in the live script that starts it
    out: list[str] = summary(live)
    for n, ps in parts.items():
        block = [f'■ [{n}] {names[n]}' + ('（脚本里没有任何地方触发它，可能是废案）' if n and n not in started else '')]
        lines = [x for p in ps for x in p.lines]
        block += [indent(x, '    ') for x in lines] if lines else ['    （没有动作）']
        for ln in [x for p in ps for x in p.links]:
            head = f'  → [{ln.target}] {names.get(ln.target, ln.name)}'
            conds = [c for c in ln.conds if not c.startswith(('//', DEAD))]
            notes = [c for c in ln.conds if c.startswith('//')]
            dropped = [c for c in ln.conds if c.startswith(DEAD)]
            joiner = ' 或 ' if ln.check == 'OR' else ' 且 '
            block.append(head + ('：' + joiner.join(conds) if conds else '：立即'))
            block += ['      ' + c for c in notes] + [DEAD + '      废案条件：' + c[len(DEAD):] for c in dropped]
        if n and n not in started:
            block = [x if x.startswith(DEAD) else DEAD + x for x in block]
        out += block + ['']
    return '\n'.join(out)


def indent(line: str, by: str) -> str:
    """Indents a digest line, keeping a dropped line's mark in front."""
    return DEAD + by + line[len(DEAD):] if line.startswith(DEAD) else by + line


# ------------------------------------------------------------------ EDF5 scripts

def digest_bvm(bvm: bytes, table: Voices) -> str:
    strings = edf5.utf16_strings(bvm)
    maps = [s for s in strings if s.lower().startswith('app:/map/')]
    objects = sorted({re.sub(r'^app:/object/|\.sgo$', '', s, flags=re.I) for s in strings if s.lower().startswith('app:/object/')})
    music = [s for s in strings if s.startswith('BGM_')]
    lines, seen = [], set()
    for s in strings:
        if s in table and s not in seen:
            seen.add(s)
            lines.append(say(s, table))
    out = ['（EDF5 的脚本是编译过的字节码，看不到事件和触发条件；下面是脚本里出现的东西。台词按脚本字符串表的顺序，不一定是播放顺序。）', '',
           '地图：' + ('、'.join(re.sub(r'^app:/map/|\.mac$', '', m, flags=re.I) for m in maps) or '（无）'),
           '音乐：' + ('、'.join(music) or '（无）'), '', '出场对象：'] + ['    ' + o for o in objects] + ['', '台词：'] + ['    ' + x for x in lines]
    return '\n'.join(out)


# ------------------------------------------------------------------ main

def header(m: dict) -> str:
    title = f'{m["series"]} {m["key"].split("/", 1)[1]} {m["sc"]}（{m["ja"]}）'
    return title + '\n' + '=' * 40 + '\n\n'


def build(root: str, out: str, only: set[str]) -> int:
    game = rootcpk.Game(root)
    table = voices(game)
    with open(MISSIONS, encoding='utf-8') as f:
        missions = json.load(f)
    os.makedirs(out, exist_ok=True)
    index: dict[str, str] = {}
    for m in missions:
        if only and m['key'] not in only:
            continue
        series, rel = m['key'].split('/', 1)
        try:
            if series == 'EDF6':
                text = digest_ac(game.read(f'MISSION/EDF6/{rel}', 'MISSION.AC').decode('utf-8-sig'), table)
            else:
                text = digest_bvm(game.read(f'MISSION/{edf5.SCRIPTS}/{rel}', 'MISSION.BVM'), table)
        except KeyError:
            print(f'跳过 {m["key"]}：Root.cpk 里没有它的脚本')
            continue
        name = m['key'].replace('/', '_') + '.txt'
        with open(os.path.join(out, name), 'w', encoding='utf-8', newline='\n') as f:
            f.write(header(m) + text)
        index[m['key']] = name
    with open(os.path.join(out, 'index.json'), 'w', encoding='utf-8') as f:
        json.dump(index, f, ensure_ascii=False, indent=1)
    print(f'{len(index)} digests -> {out}')
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('game', nargs='?', default=rootcpk.DEFAULT_GAME)
    ap.add_argument('--out', default=OUT)
    ap.add_argument('--only', nargs='*', default=[])
    a = ap.parse_args(argv)
    return build(a.game, os.path.normpath(a.out), set(a.only))


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
