"""Readable digests of the stock mission scripts, for discussing changes on the test site (testhub, level plan).

  python -B tools/make_mission_digest.py [GAME_DIR] [--out DIR] [--only KEY ...]

Made on this machine from the player's own Root.cpk and uploaded to the logged-in site with
`python tools/testhub.py digests DIR`; never committed (the repository is public and the scripts are the game's).

EDF6 missions (MISSION/EDF6/<id>/MISSION.AC, AngelScript generated by the developers' event editor): one block per
event, in event order: its name, what it does (the script with the editor's scaffolding, loading, lighting and
commented-out code taken out), the lines it speaks (voice ids replaced by speaker and Simplified Chinese caption
from MISSION/EDF6_VOICETABLE*.SGO), and the events it starts with their conditions (well-known Factor_* calls
put in words, the call kept beside them; the others as written).

EDF5 missions (MISSION/EDF5_OLD_SCRIPT/<id>/MISSION.BVM, compiled): no event structure survives, so only what the
string pool shows: maps, objects, music, and the voice lines in string-pool order (not necessarily play order).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'pylib'))
sys.path.insert(0, HERE)
import dsgo  # noqa: E402
import make_edf5_campaign as edf5  # noqa: E402
import rootcpk  # noqa: E402
import sgo  # noqa: E402

MISSIONS = os.path.join(HERE, '..', 'testhub', 'src', 'missions.json')
OUT = os.path.join(HERE, '..', 'tmp', 'digests')

# ------------------------------------------------------------------ voices

Voices = dict[str, tuple[str, str]]


def voices(game: rootcpk.Game) -> Voices:
    """Voice id -> (speaker, SC caption): the id table names each row index, the language table holds the row."""
    ids = dsgo.parse(game.read('MISSION', 'EDF6_VOICETABLE.SGO')).root.items[0]
    rows = dsgo.parse(game.read('MISSION', 'EDF6_VOICETABLE.SC.SGO')).root.items[0].items
    out: Voices = {}
    for i, vid in ids.names.items():
        if i < len(rows) and isinstance(rows[i], dsgo.Node) and len(rows[i].items) >= 2:
            out[vid] = (str(rows[i].items[0]), str(rows[i].items[1]).replace('\n', ' '))
    return out


def say(vid: str, table: Voices) -> str:
    who, text = table[vid]
    return f'{who}：「{text}」'


# ------------------------------------------------------------------ names

# The soldier classes and the game's own text for their class (TEXTTABLE SoldierType_*): soldiers carry no kill
# counter, so their class is the only name the game gives them.
SOLDIER_CLASSES = {'AssultSoldier': 'Ranger', 'PaleWing': 'WingDiver', 'HeavyArmor': 'Fencer', 'Engineer': 'AirRaider'}


class Names:
    """Simplified Chinese names the game itself gives (nothing here is translated by us):
    - an enemy: its OBJECT/<name>.SGO `game_object_kill_counter` X -> ETC/TEXTTABLE_STEAM.SC.TXT_SGO 'StatusInfo_' + X
      ('侵略生物α击破数', the kill statistics) without its '击破数': the species, so variants share a name;
    - a soldier (or a named character of a soldier class): its `xgs_scene_object_class` -> SoldierType_*, as '兵种：…';
    - a map: the game has no map names, so the first mission (in the plan's order) that loads it, said as such.
    Objects are spread over Root.cpk, Chunk01.cpk and Chunk02.cpk."""

    def __init__(self, root: str) -> None:
        self.archives = [rootcpk.Game(root, a) for a in ('Root.cpk', 'Chunk01.cpk', 'Chunk02.cpk')
                         if os.path.isfile(os.path.join(root, a))]
        self.text: dict = sgo.read(self.archives[0].read('ETC', 'TEXTTABLE_STEAM.SC.TXT_SGO'))[1]
        self.cache: dict[str, str | None] = {}
        self.map_first: dict[str, str] = {}

    def _object(self, name: str) -> dict:
        for g in self.archives:
            try:
                data = g.read('OBJECT', name + '.SGO')
            except KeyError:
                continue
            if data[:4] == b'DSGO':
                r = dsgo.parse(data).root
                return {r.names.get(i): x for i, x in enumerate(r.items)}
            return sgo.read(data)[1]
        return {}

    def object(self, name: str) -> str | None:
        key = name.lower()
        if key not in self.cache:
            info = self._object(name)
            counter, cls = info.get('game_object_kill_counter'), info.get('xgs_scene_object_class')
            text = self.text.get(f'StatusInfo_{counter}') if counter else None
            soldier = self.text.get(f'SoldierType_{SOLDIER_CLASSES[cls]}') if cls in SOLDIER_CLASSES else None
            self.cache[key] = (str(text).removesuffix('击破数') if text else None) or (f'兵种：{soldier}' if soldier else None)
        return self.cache[key]

    def label(self, name: str) -> str:
        sc = self.object(name)
        return f'{name}（{sc}）' if sc else name

    def map(self, name: str) -> str:
        first = self.map_first.get(name.lower())
        return f'{name}（游戏里没有地图名；最早用到它的任务：《{first}》）' if first else name


# ------------------------------------------------------------------ EDF6 scripts

TEAMS = {'TEAM_ID_ENEMY': '敌方', 'TEAM_ID_FRIEND': '友方', 'TEAM_ID_PLAYER': '玩家方'}
LEVELS = {'MISSION_DIFFICULTY_EASY': '简单', 'MISSION_DIFFICULTY_NORMAL': '普通', 'MISSION_DIFFICULTY_HARD': '困难',
          'MISSION_DIFFICULTY_HARDEST': '极难', 'MISSION_DIFFICULTY_INFERNO': '炼狱'}


def _args(text: str) -> list[str]:
    """Top-level arguments of a call's text 'Name(a, f(b, c), "d,e")' (comments already removed)."""
    inner = text[text.index('(') + 1:text.rindex(')')]
    out, depth, cur, quote = [], 0, '', False
    for ch in inner:
        if ch == '"':
            quote = not quote
        if not quote and ch in '([{':
            depth += 1
        if not quote and ch in ')]}':
            depth -= 1
        if ch == ',' and depth == 0 and not quote:
            out.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def _plain(a: str) -> str:
    a = a.strip().strip('"')
    return TEAMS.get(a, LEVELS.get(a, a))


# Factor_* calls whose meaning is plain from the name and the editor's own argument labels.
FACTORS = {
    'Factor_Wait': lambda a: f'等 {a[0]} 秒',
    'Factor_PlayerAreaIn': lambda a: f'玩家进入区域「{_plain(a[0])}」',
    'Factor_TeamEncount': lambda a: f'{_plain(a[0])}进入交战',
    'Factor_TeamNotEncount': lambda a: f'{_plain(a[0])}不在交战',
    'Factor_TeamObjectCount': lambda a: f'{_plain(a[0])}存活数 ≤ {a[1]}',
    'Factor_TeamBigObjectCount': lambda a: f'{_plain(a[0])}大型目标存活数 ≤ {a[1]}',
    'Factor_GroupObjectCount': lambda a: f'{a[0]} 组存活数 ≤ {a[1]}',
    'Factor_AiMoveEnd': lambda a: f'{a[0]} 走完路线',
    'Factor_AiMoveEndOrDie': lambda a: f'{a[0]} 走完路线或阵亡',
    'Factor_ObjectDestroy': lambda a: f'{a[0]} 被摧毁',
    'Factor_PlayerObjectDistance': lambda a: f'玩家离 {a[0]} ≤ {a[1]} 米',
    'Factor_FlagOn': lambda a: f'标志 {a[0]} 打开',
    'Factor_FlagOff': lambda a: f'标志 {a[0]} 关闭',
    'Factor_DifficultyOverEqu': lambda a: f'难度 ≥ {_plain(a[0])}',
    'Factor_DifficultyLessEqu': lambda a: f'难度 ≤ {_plain(a[0])}',
    'Factor_RideVehicle': lambda a: '玩家上了载具' if not a else f'上了载具 {", ".join(a)}',
    'Factor_IsOnlineMode': lambda a: '联机时',
    'Factor_IsRetry': lambda a: '重试时',
    'Factor_IsNotRetry': lambda a: '不是重试时',
}

# Statements that are the event editor's scaffolding or loading/lighting detail, not the mission's content.
NOISE = re.compile(r'^(::|internal_|__|IsBoolState|Mutex_|WaitVoice\(\)|g_soldiers\s*=\s*GetTalkers|Preload|WaitPreload|'
                   r'BeginLoading|EndLoading|Online_WaitStart|EventLightTool\b|tool\.|const uint32 MAX_EVENT_ID|'
                   r'\w+_usercode\(\);|if\(\s*::__\w+_data\.m_counter\b)')
# Only the editor's own guard (`if( ::__XXXX_data.m_counter != 1 ) return;`) goes: a script's own `if (...) return;`
# is a condition the reader needs.
# Dropped ideas (code switched off, debug-only placeholder text, superseded dialogue, events nothing starts) are
# kept but marked: a digest line starting with DEAD is shown greyed on the site.
DEAD = '⊘ '
DEAD_COMMENT = '//⊘ '
DEBUG_TEXT = re.compile(r'^DebugMessageW\(\s*"([^"]*)"')
# Presentation only (animation, facing, camera, chatter switches): left out of the digest.
SHOW = re.compile(r'(^|\.)(AppealAnimation\w*|SetAiObjectDirection_\w+|ClearAiObjectDirection|LookCameraTo\w+|CloseUi|'
                  r'SetCharacterRandomTalk|EnableAiRandomTalk|DisableAiRandomTalk|TalkBegin|TalkEnd|EnvFadeAnimation)\s*\(')
# A // comment that is code switched off rather than a note.
CODE_COMMENT = re.compile(r'^//\s*([A-Za-z_:][A-Za-z0-9_.:\[\]]*\s*(\(|=[^=])|[A-Za-z_:].*;\s*(//.*)?$)', re.ASCII)
# ASCII identifiers only: a Japanese note like `// 増援(2波目)` or `// 敵数=10` is a note, not switched-off code.
SPEECH = re.compile(r'^(Speak_\w+|RadioVoice|Talk_\w+)\s*\(')
NUM_F = re.compile(r'\b(\d+(?:\.\d+)?)f\b')
DROP_COMMENTS = re.compile(r'^//\s*(\[e2d_section_data\]|ゲーム進行スクリプト|音声スクリプト|-{5,})')
EVENT = re.compile(r'internal_CreateEvent\(\s*"__([0-9A-Fa-f]{4})_game_event"\s*,\s*"([^"]*)"\s*,[^,]*,\s*(EVENT_TYPE_\w+)\s*,\s*(EVENT_CHECK_\w+)')


def mark_block_comments(text: str) -> str:
    """/* ... */ spanning lines or longer than a label is code the developers switched off: each of its lines
    becomes a `//⊘` comment (shown greyed as a dropped idea). One-line argument labels /*名*/ stay as they are."""
    def mark(m: re.Match) -> str:
        body = m.group(0)[2:-2]
        if '\n' not in body and len(body) <= 30:
            return f'/*{body.strip()}*/'
        return '\n' + '\n'.join(DEAD_COMMENT + x.strip() for x in body.split('\n') if x.strip()) + '\n'
    return re.sub(r'/\*.*?\*/', mark, text, flags=re.S)


def functions(text: str) -> dict[str, str]:
    """Top-level function bodies by name, brace matched outside // comments and strings (switched-off code in
    comments holds braces)."""
    out: dict[str, str] = {}
    for m in re.finditer(r'^void\s+(\w+)\s*\(\s*\)\s*\n\{', text, flags=re.M):
        depth, i = 1, m.end()
        while depth and i < len(text):
            c = text[i]
            if c == '/' and text.startswith('//', i):
                i = text.find('\n', i)
                i = len(text) if i < 0 else i
                continue
            if c == '"':
                i = text.find('"', i + 1) + 1 or len(text)
                continue
            depth += {'{': 1, '}': -1}.get(c, 0)
            i += 1
        out[m.group(1)] = text[m.end():i - 1]
    return out


def statements(body: str) -> list[tuple[int, str]]:
    """(indent, statement) with multi-line calls joined; a continuation line's // comment becomes /*...*/ after its
    own argument. Switched-off code (`//⊘` lines, // comments that are code, and the lines continuing such a
    call) is joined the same way and comes out as one `//⊘` statement."""
    out: list[tuple[int, str]] = []
    pending: list | None = None   # [indent, text, depth, dead]

    def flush() -> None:
        nonlocal pending
        if pending:
            out.append((pending[0], (DEAD_COMMENT if pending[3] else '') + pending[1]))
        pending = None

    for raw in body.split('\n'):
        line = raw.strip()
        if not line:
            continue
        indent = len(raw) - len(raw.lstrip('\t'))
        dead = False
        if line.startswith(DEAD_COMMENT.strip()):
            dead, line = True, line[len(DEAD_COMMENT.strip()):].strip()
        elif line.startswith('//') and (CODE_COMMENT.match(line) or (pending and pending[3])):
            dead, line = True, line[2:].strip()
        if pending and dead != pending[3]:
            flush()
        if pending:
            code, _, note = line.partition('//')
            code = code.strip()
            label = f' /*{note.strip()}*/' if note.strip() else ''
            pending[1] += ' ' + (code[:-1] + label + ',' if label and code.endswith(',') else code + label)
            pending[2] += code.count('(') - code.count(')')
            if pending[2] <= 0:
                flush()
            continue
        if not dead and line.startswith('//'):
            out.append((indent, line))
            continue
        code = line.split('//')[0]
        d = code.count('(') - code.count(')')
        if d > 0:
            pending = [indent, code.strip(), d, dead]
            continue
        out.append((indent, (DEAD_COMMENT if dead else '') + line))
    flush()
    return out


@dataclass
class Link:
    target: int
    name: str
    check: str
    conds: list[str] = field(default_factory=list)


@dataclass
class Part:
    lines: list[str] = field(default_factory=list)
    links: list[Link] = field(default_factory=list)


def factor(call: str) -> str:
    name = call.split('(')[0].split('.')[-1]
    plain = re.sub(r'/\*.*?\*/', '', call)
    try:
        args = [NUM_F.sub(r'\1', x) for x in _args(plain)]
        if name in FACTORS:
            return f'{FACTORS[name](args)}（{name}）'
    except (IndexError, ValueError):
        pass
    return NUM_F.sub(r'\1', plain.removeprefix('e.').rstrip(';').strip())


def readable(stmt: str) -> str:
    return NUM_F.sub(r'\1', re.sub(r'"app:/(?:object|Object)/([^"]+?)\.sgo"', r'\1', stmt))


# Spawning calls: for each object argument (by position), where its count is: an argument position, or ONE.
# Positions come from the editor's own argument labels (作成数 / 発生数 / 数 / 部下の数) in the stock scripts.
ONE = -1
SPAWNS: dict[str, dict[int, int]] = {
    'CreateEnemy': {1: ONE}, 'CreateEnemy2': {1: ONE}, 'CreateFriend': {1: ONE}, 'CreateNeutral': {1: ONE},
    'CreateVehicle': {1: ONE}, 'CreateVehicle2': {1: ONE}, 'EDF6_GrandMother_CreateParts': {2: ONE},
    'CreateEnemyGroup_Area': {1: 2}, 'CreateFlyingEnemyGroup_Area': {1: 2}, 'CreateEnemyGroup_Area_Spawn': {1: 2},
    'InstantGenerateEnemy_Area': {1: 2}, 'EDF6_TimeShip_CreatePodCrue': {1: 2},
    'CreateEnemyGroup': {2: 3}, 'CreateEnemyGroupUG': {2: 3}, 'CreateFriendGroup': {2: 3}, 'CreateColonelSquad': {2: 3},
    'CreateFlyingEnemyGroup_OnRoute': {2: 3},
    'CreateFriendSquad': {2: ONE, 3: 4}, 'CreateLieutenantSquad': {2: ONE, 3: 4}, 'CreateEscapeSquad': {2: ONE, 3: 4},
    'CreateEnemySquad': {2: ONE, 4: 5}, 'CreateFlyingEnemySquad_Area': {1: ONE, 3: 4},
    'DropBoat_SetCrew': {0: ONE, 2: 3}, 'SetDropBoatCrew': {1: ONE, 3: 4},
    'SetInstantEnemyGenerator': {1: 2},
}
GENERATORS = {'SetEnemyGenerator': (1, 2)}   # object, count per wave: it keeps spawning waves


@dataclass
class Count:
    n: int = 0             # objects spawned by literal counts, added over every live call
    unknown: bool = False  # some count is a variable or an expression
    waves: list[int | str] = field(default_factory=list)   # a generator's count per wave


def _object(arg: str) -> str | None:
    m = re.fullmatch(r'"app:/object/([^"]+?)\.sgo"', arg.strip(), flags=re.I)
    return m.group(1) if m else None


def _one_call(s: str, open_at: int) -> str | None:
    """'(...)' of the call whose '(' is at open_at, up to its own ')' (not a chained call's)."""
    depth, quote = 0, False
    for i in range(open_at, len(s)):
        ch = s[i]
        if ch == '"':
            quote = not quote
        elif not quote and ch == '(':
            depth += 1
        elif not quote and ch == ')':
            depth -= 1
            if depth == 0:
                return s[open_at:i + 1]
    return None


def spawn_counts(live: str) -> dict[str, Count]:
    out: dict[str, Count] = {}
    for _, s in statements(live):
        if s.startswith('//'):
            continue
        for m in re.finditer(r'\b(\w+)\s*\(', s):
            fn = m.group(1)
            if fn not in SPAWNS and fn not in GENERATORS:
                continue
            call = _one_call(s, m.end() - 1)
            if call is None:
                continue
            args = [re.sub(r'/\*.*?\*/', '', a).strip() for a in _args(call)]
            pairs = SPAWNS.get(fn) or {GENERATORS[fn][0]: GENERATORS[fn][1]}
            for at, count_at in pairs.items():
                obj = _object(args[at]) if at < len(args) else None
                if not obj:
                    continue
                c = out.setdefault(obj, Count())
                raw = '1' if count_at == ONE else args[count_at] if count_at < len(args) else ''
                literal = NUM_F.sub(r'\1', raw)
                if fn in GENERATORS:
                    c.waves.append(int(literal) if literal.isdigit() else literal or '?')
                elif literal.isdigit():
                    c.n += int(literal)
                else:
                    c.unknown = True
    return out


def count_text(c: Count) -> str:
    parts = [f'×{c.n}' if c.n else '']
    if c.unknown:
        parts.append('另有数量写成变量的' if c.n else '数量写成变量')
    if c.waves:
        parts.append('生成器每波 ' + '/'.join(str(w) for w in c.waves) + ' 只、持续刷出')
    return '，'.join(p for p in parts if p)


AC_MAP = re.compile(r'\bMap\(\s*"app:/map/([^"]+?)\.mac"\s*,\s*"([^"]*)"', flags=re.I)
NAME_NOTE = '（括号里是游戏自己的叫法：敌人取自击破统计，同一种类的变体同名；士兵和角色给的是兵种；游戏没给名字的保留原名）'


def summary(text: str, names: Names) -> list[str]:
    """The map and every object the live script creates or spawns (with how many), before the event walk."""
    maps = sorted(set(AC_MAP.findall(text)))
    counts = spawn_counts(text)
    others = sorted({o for o in re.findall(r'"app:/object/([^"]+?)\.sgo"', text, flags=re.I)} - counts.keys(), key=str.lower)
    out = ['地图：' + ('、'.join(f'{names.map(m)}，{w}' for m, w in maps) or '（无）'), '',
           '出场对象（数量是脚本里每一处刷出相加；按难度分支、循环没有展开，只作参考）：', '  ' + NAME_NOTE]
    out += [f'    {names.label(o)}  {count_text(c)}' for o, c in sorted(counts.items(), key=lambda kv: kv[0].lower())] or ['    （无）']
    if others:
        out.append('其它引用到的对象（预载、特效、变量里的写法等，数量不明）：' + '、'.join(names.label(o) for o in others))
    return out + ['']


def part(body: str, table: Voices) -> Part:
    """An event's usercode: its own statements, then the links it registers (`{ ... CreateEvent ...; e.Factor_...; }`)."""
    out = Part()
    base = None
    link: Link | None = None
    notes: list[str] = []   # comments waiting for the statement they describe
    for indent, s in statements(body):
        if DROP_COMMENTS.match(s) or s in ('{', '}', '};'):
            continue
        dead = s[len(DEAD_COMMENT):].strip() if s.startswith(DEAD_COMMENT) else None
        if dead is not None:
            if link:   # a condition switched off
                link.conds.append(DEAD + (factor(dead) if dead.startswith('e.Factor_') else dead))
                continue
            code = dead.lstrip('{} ')
            if not code or NOISE.match(code) or SHOW.search(code) or DROP_COMMENTS.match(code):
                continue
        else:
            code = s.lstrip('{} ')
        m = EVENT.search(s) if dead is None else None
        if m:
            notes = []
            link = Link(int(m.group(1), 16), m.group(2), 'OR' if m.group(4).endswith('OR') else 'AND')
            out.links.append(link)
            continue
        if dead is None and s.startswith('e.Factor_') and link:
            link.conds.append(factor(s))
            continue
        if dead is None and link and s.startswith('//'):
            link.conds.append(s)
            continue
        if dead is None and (s.startswith('if( IsBoolState') or NOISE.match(code) or SHOW.search(code)):
            notes = []   # the notes were about what is left out
            continue
        link = None
        if base is None:
            base = indent
        pad = '  ' * max(0, indent - base)
        if dead is None and s.startswith('//'):
            notes.append(pad + s)
            continue
        out.lines += notes
        notes = []
        out.lines += statement_lines(code if dead is None else dead, pad, table, dead is not None)
    out.lines += notes
    return out


def statement_lines(s: str, pad: str, table: Voices, dead: bool) -> list[str]:
    """One kept statement: dialogue as its caption (with the superseded draft line in its trailing comment marked
    as dropped), debug-only text as dropped, anything else as written."""
    mark = DEAD if dead else ''
    debug = DEBUG_TEXT.match(s)
    if debug:
        return [DEAD + pad + '调试文字：' + debug.group(1)]
    code, _, trailing = s.partition('//')
    said = [vid for vid in re.findall(r'"([A-Z]{1,3}\d{3}_[0-9A-Z]+)"', code) if vid in table]
    head = code.split('(')[0]
    if said and SPEECH.match(head.split('.')[-1] + '('):
        out = [mark + pad + '说：' + say(vid, table) for vid in said]
        if trailing.strip():
            out.append((DEAD + pad + '旧稿：' if '「' in trailing else mark + pad + '//') + trailing.strip())
        return out
    return [mark + pad + readable(s.rstrip('{').rstrip())] + [mark + pad + '    ' + say(vid, table) for vid in said]


def digest_ac(text: str, table: Voices, names: Names) -> str:
    text = mark_block_comments(text)
    events = {int(n): v for n, v in re.findall(r'internal_GetEventState\((\d+)\)\.SetName\("([^"]*)"\)', text)}
    fns = functions(text)
    # An event's links are registered in its usercode and also in its wrapper (__XXXX_game_event / Main), which
    # starts some of them as soon as the event runs.
    parts = {n: [part(fns.get(f, ''), table) for f in (
        ('Main', 'Main_usercode') if n == 0 else (f'__{n:04X}_game_event', f'__{n:04X}_game_event_usercode')
    ) + (f'__{n:04X}_voice_event_usercode',)] for n in sorted(events)}
    live = re.sub(r'^\s*//.*$', '', text, flags=re.M)
    started = {int(h, 16) for h, *_ in EVENT.findall(live)}   # anything in the live script that starts it
    out: list[str] = summary(live, names)
    for n, ps in parts.items():
        block = [f'■ [{n}] {events[n]}' + ('（脚本里没有任何地方触发它，可能是废案）' if n and n not in started else '')]
        lines = [x for p in ps for x in p.lines]
        block += [indent(x, '    ') for x in lines] if lines else ['    （没有动作）']
        for ln in [x for p in ps for x in p.links]:
            head = f'  → [{ln.target}] {events.get(ln.target, ln.name)}'
            conds = [c for c in ln.conds if not c.startswith(('//', DEAD))]
            notes = [c for c in ln.conds if c.startswith('//')]
            dropped = [c for c in ln.conds if c.startswith(DEAD)]
            joiner = ' 或 ' if ln.check == 'OR' else ' 且 '
            block.append(head + ('：' + joiner.join(conds) if conds else '：立即'))
            block += ['      ' + c for c in notes] + [DEAD + '      废案条件：' + c[len(DEAD):] for c in dropped]
        if n and n not in started:
            block = [x if x.startswith(DEAD) else DEAD + x for x in block]
        out += block + ['']
    return '\n'.join(out)


def indent(line: str, by: str) -> str:
    """Indents a digest line, keeping a dropped line's mark in front."""
    return DEAD + by + line[len(DEAD):] if line.startswith(DEAD) else by + line


# ------------------------------------------------------------------ EDF5 scripts

def bvm_maps(bvm: bytes) -> list[str]:
    return [re.sub(r'^app:/map/|\.mac$', '', s, flags=re.I) for s in edf5.utf16_strings(bvm) if s.lower().startswith('app:/map/')]


def digest_bvm(bvm: bytes, table: Voices, names: Names) -> str:
    strings = edf5.utf16_strings(bvm)
    objects = sorted({re.sub(r'^app:/object/|\.sgo$', '', s, flags=re.I) for s in strings if s.lower().startswith('app:/object/')},
                     key=str.lower)
    music = [s for s in strings if s.startswith('BGM_')]
    lines, seen = [], set()
    for s in strings:
        if s in table and s not in seen:
            seen.add(s)
            lines.append(say(s, table))
    out = ['（EDF5 的脚本是编译过的字节码，看不到事件和触发条件，也读不出刷怪数量；下面是脚本里出现的东西。台词按脚本字符串表的顺序，不一定是播放顺序。）', '',
           '地图：' + ('、'.join(names.map(m) for m in bvm_maps(bvm)) or '（无）'),
           '音乐：' + ('、'.join(music) or '（无）'), '', '出场对象：', '  ' + NAME_NOTE]
    out += ['    ' + names.label(o) for o in objects] + ['', '台词：'] + ['    ' + x for x in lines]
    return '\n'.join(out)


# ------------------------------------------------------------------ main

def header(m: dict) -> str:
    title = f'{m["series"]} {m["key"].split("/", 1)[1]} {m["sc"]}（{m["ja"]}）'
    return title + '\n' + '=' * 40 + '\n\n'


def script(game: rootcpk.Game, key: str) -> str | bytes | None:
    """An EDF6 mission's MISSION.AC text or an EDF5 one's MISSION.BVM bytes; None when Root.cpk lacks it."""
    series, rel = key.split('/', 1)
    try:
        if series == 'EDF6':
            return game.read(f'MISSION/EDF6/{rel}', 'MISSION.AC').decode('utf-8-sig')
        return game.read(f'MISSION/{edf5.SCRIPTS}/{rel}', 'MISSION.BVM')
    except KeyError:
        return None


def build(root: str, out: str, only: set[str]) -> int:
    game = rootcpk.Game(root)
    table = voices(game)
    names = Names(root)
    with open(MISSIONS, encoding='utf-8') as f:
        missions = json.load(f)
    scripts = {m['key']: script(game, m['key']) for m in missions}
    for m in missions:   # every map's first mission in the plan's order (the game has no map names)
        s = scripts[m['key']]
        for map_name in ([x for x, _ in AC_MAP.findall(s)] if isinstance(s, str) else bvm_maps(s) if s else []):
            names.map_first.setdefault(map_name.lower(), f'{m["series"]} {m["key"].split("/")[-1]} {m["sc"]}')
    os.makedirs(out, exist_ok=True)
    index: dict[str, str] = {}
    for m in missions:
        if only and m['key'] not in only:
            continue
        s = scripts[m['key']]
        if s is None:
            print(f'跳过 {m["key"]}：Root.cpk 里没有它的脚本')
            continue
        text = digest_ac(s, table, names) if isinstance(s, str) else digest_bvm(s, table, names)
        name = m['key'].replace('/', '_') + '.txt'
        with open(os.path.join(out, name), 'w', encoding='utf-8', newline='\n') as f:
            f.write(header(m) + text)
        index[m['key']] = name
    with open(os.path.join(out, 'index.json'), 'w', encoding='utf-8') as f:
        json.dump(index, f, ensure_ascii=False, indent=1)
    print(f'{len(index)} digests -> {out}')
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('game', nargs='?', default=rootcpk.DEFAULT_GAME)
    ap.add_argument('--out', default=OUT)
    ap.add_argument('--only', nargs='*', default=[])
    a = ap.parse_args(argv)
    return build(a.game, os.path.normpath(a.out), set(a.only))


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
