// Generated by tools/gen_nozzles.py from the stock models in Root.cpk (pylib/jet_models.py STOCK_BOMBERS,
// NOZZLE_EXITS, exit_nozzles). Do not edit: python tools/gen_nozzles.py (with the game) rewrites it.
// data: {"inputs":{"exits":{"bomber401":[[[2.0,5.8],[0.8,2.15],[-2.0,-0.2]],true],"bomber501_2":[[[1.5,5.6],[-2.3,2.3],[-12.95,-11.69]],true]},"flame_length_per_diameter":5.0,"version":1},"models":{"bomber401":{"bones":2,"flame":[[7.3881,1.4776],[7.3881,1.4776]],"local":[[-1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,3.831158,1.440475,-0.913391,1.0],[-1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,-3.831158,1.440475,-0.913391,1.0]],"parent":"bomber401","sha256":"f9428ba1dc5ca472d6ca1bbfd8992bdcfa09171944dc1cf34c76a4255f098ee9"},"bomber501_2":{"bones":3,"flame":[[9.1943,1.8389],[9.1943,1.8389]],"local":[[-1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,3.579561,0.03942,-12.005682,1.0],[-1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,-3.579561,0.03942,-12.005682,1.0]],"parent":"bomber501","sha256":"871133280d95954026e59d153e8e3c01480f886f2edb4df89965e2841576c5b6"}}}
#pragma once

namespace crew::exhaust {
// {the model's own bone, its bone count, the bone the nozzles hang on, how many, each one's local matrix on it,
//  each one's flame (length, width)}
inline constexpr StockNozzles kStockNozzles[]={
    {L"bomber401",2,L"bomber401",2,{{-1.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f,-1.0f,0.0f,3.83116f,1.44047f,-0.913391f,1.0f},{-1.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f,-1.0f,0.0f,-3.83116f,1.44047f,-0.913391f,1.0f}},{{7.3881f,1.4776f},{7.3881f,1.4776f}}},
    {L"bomber501_2",3,L"bomber501",2,{{-1.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f,-1.0f,0.0f,3.57956f,0.03942f,-12.0057f,1.0f},{-1.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,0.0f,0.0f,0.0f,-1.0f,0.0f,-3.57956f,0.03942f,-12.0057f,1.0f}},{{9.1943f,1.8389f},{9.1943f,1.8389f}}},
};
}  // namespace crew::exhaust
