"""潜舰对战母舰: the offline mission M082 (list item 104, 潜艇母舰‧保卫作战, the coast where the stock
submarine carrier surfaces next to the Mothership) remade with only the plugin's submarine carrier against
the Mothership. Same map, weather and points as M082 (its MISSION.RMPA copied as it is):

  - the player at the stock start (プレイヤー, on the cliff);
  - the submarine carrier (tools/make_sub.py EDF6VC_SUB_CARRIER.SGO, 1664 m, flown by EDF6VehicleCrew's
    src/subcarrier.cpp) at the stock carrier's point 潜水母艦近５, 2 km out at sea;
  - the Mothership (e511_mothership_light, as M082 makes it): its core hatch opens at once, the Genocide
    cannon attacks on its own, and it drops gold UFOs. The Genocide cannon is what is fought (M082: the
    Mothership itself stays invincible); once it is destroyed the Mothership blows itself up, as in M082,
    and the mission is cleared.

Writes Mods/MISSION/EDF6/M082 (MISSION.AC, MISSION.RMPA and the marker) and nothing else; refuses a folder
another mod put there; --remove deletes it only when the marker is there. The submarine's files come from
tools/make_sub.py (run it first, with the game closed).

  python testrange/sub_vs_mothership.py [game dir]
  python testrange/sub_vs_mothership.py [game dir] --remove
"""
from __future__ import annotations

import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, 'lib'))
sys.path.insert(0, HERE)
import gen  # noqa: E402

MISSION = 'M082'
ITEM = 104
MARKER = 'EDF6SubVsMothership.txt'
MAP = 'app:/map/ig_SteepCoast.mac'
WEATHER = 'afternoon'
SUB = 'app:/object/edf6vc_sub_carrier.sgo'
SUB_FILES = ('EDF6VC_SUB_CARRIER.SGO', 'EDF6VC_SUB.MRAB')
MOTHER = 'app:/object/e511_mothership_light.sgo'
UFO = 'app:/object/e507_goldufo.sgo'


def _q(text: str) -> str:
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def script() -> str:
    """The mission: the stock skeleton (event 0 = Main, as gen.script), run straight through."""
    preload = [MOTHER, UFO, SUB]
    return '\n'.join([
        '//',
        '// 潜舰对战母舰, generated by testrange/sub_vs_mothership.py (EDF6VehicleCrew). Delete this folder to',
        '// restore M082.',
        '//',
        '',
        '#include "app:/Mission/AsCommon.h"',
        '',
        'Talkers g_soldiers;',
        'Object mother;',
        'Object cannon;',
        '',
        'class __EventData {',
        '\tuint m_counter  = 0;',
        '\tbool m_is_break = false;',
        '\tbool m_is_pass = false;',
        '\tinternal_SyncCounter m_game_thread_sync;',
        '\tinternal_SyncCounter m_voice_thread_sync;',
        '\tMutex m_mutex;',
        '};',
        '',
        '__EventData __0000_data;',
        '',
        'const uint __END_SYNC = 0x7fffffff;',
        '',
        'void Main()',
        '{',
        '\tif( IsBoolState(0,::__0000_data.m_is_break,::__0000_data.m_is_break) ) return;',
        '\t::__0000_data.m_counter++;',
        '\tconst uint32 MAX_EVENT_ID = 1;',
        '\tinternal_Initialize(MAX_EVENT_ID);',
        '\tinternal_GetEventState(0).SetName("開始");',
        '\tMutex_LockObject@ __internal_thread_lock = ::__0000_data.m_mutex.Lock();',
        '\tinternal_InitEventThread(0, ::__0000_data.m_counter, "Main", "開始");',
        '',
        '\tBeginLoading();',
        f'\tPreloadMap({_q(MAP)}, {_q(WEATHER)}, -1);',
        '\tPreload("app:/ui/UiResourceGroup_InMission.sgo", -1);',
        '\tPreload("app:/ui/UiResourceGroup_MissionCleared.sgo", -1);',
        '\tPreload("app:/ui/UiResourceGroup_MissionFailed.sgo", -1);',
        *[f'\tPreload({_q(p)}, -1);' for p in preload],
        '\tPreloadPlayerResource();',
        '\tWaitPreload();',
        '\tOnline_WaitStart();',
        '\tEndLoading();',
        '',
        '\tWaitVoice();',
        '\tg_soldiers = GetTalkers();',
        '\t::__0000_data.m_game_thread_sync.Reset();',
        '\t::__0000_data.m_voice_thread_sync.Reset();',
        '\t::internal_CreateThread("__0000_voice_event");',
        '',
        '\tMain_usercode();',
        '',
        '\t::__0000_data.m_game_thread_sync.Update(__END_SYNC);',
        '\t::__0000_data.m_voice_thread_sync.Wait(__END_SYNC);',
        '}',
        '',
        'void Main_usercode()',
        '{',
        f'\tMap({_q(MAP)}, {_q(WEATHER)});',
        '\tCreatePlayer("プレイヤー");',
        '',
        '\t// The submarine carrier: flown by the plugin (not in the squad).',
        f'\tCreateFriend("潜水母艦近５", {_q(SUB)}, 1.00, false);',
        '',
        '\t// The Mothership as M082 makes it: the body invincible, the Genocide cannon what is fought.',
        f'\tmother = CreateEnemy("マザーシップ", {_q(MOTHER)}, 1, true).SetInvincible(true);',
        '\tmother.Action(UFO_MOTHER511_ACTION_LIGHT_WEIGHT_EXPLOSION);',
        '\tcannon = mother.GetPartsObject(UFO_MOTHER511_PARTS_TYPE_CORE_BIG_CANNON, 0);',
        '\tcannon.SetDurability(150);',
        '',
        '\tWait(15.0);',
        '\tmother.Action(UFO_MOTHER511_ACTION_CORE_HATCH_OPEN);',
        '\tmother.Action(UFO_MOTHER511_ACTION_GENOCIDE_AUTO_ATTACK);',
        '\tmother.SetAiRoute("マザーシップ巡回").SetAiMoveSpeed(0.3);',
        f'\tmother.SetEnemyGenerator(0, {_q(UFO)}, 8, 1, 0.5f, 70, true);',
        '',
        '\twhile( cannon.IsAlive() ) Wait(1.0);',
        '\tmother.Suicide();',
        '\tWait(8.0);',
        '\tMissionClear();',
        '\twhile( true ) sys_Yield();',
        '}',
        '',
        'void __0000_voice_event()',
        '{',
        '\t::__0000_data.m_voice_thread_sync.Update(__END_SYNC);',
        '\t::__0000_data.m_game_thread_sync.Wait(__END_SYNC);',
        '}',
        '',
    ])


def ours(out: str) -> bool:
    return os.path.isfile(os.path.join(out, MARKER))


def install(root: str) -> str:
    out = gen.mission_dir(root, MISSION)
    if os.path.isdir(out) and os.listdir(out) and not ours(out):
        raise RuntimeError(f'{out} 已有别的 mod 的文件，不覆盖。')
    missing = [f for f in SUB_FILES if not os.path.isfile(os.path.join(gen.object_dir(root), f))]
    if missing:
        raise RuntimeError(f'缺少潜舰文件 {missing}：游戏关闭时先运行 python tools/make_sub.py')
    game = gen.Game(root)
    points = game.read(f'MISSION/EDF6/{MISSION}', 'MISSION.RMPA')
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, 'MISSION.AC'), 'wb') as f:
        f.write(b'\xef\xbb\xbf' + script().encode('utf-8'))
    with open(os.path.join(out, 'MISSION.RMPA'), 'wb') as f:
        f.write(points)
    with open(os.path.join(out, MARKER), 'w', encoding='utf-8') as f:
        f.write('潜舰对战母舰（EDF6VehicleCrew/testrange/sub_vs_mothership.py）。删除本目录即恢复 M082。\n')
    return out


def remove(root: str) -> bool:
    out = gen.mission_dir(root, MISSION)
    if not ours(out):
        return False
    shutil.rmtree(out)
    return True


def main(argv: list[str]) -> int:
    args = [a for a in argv if not a.startswith('--')]
    root = args[0] if args else gen.DEFAULT_GAME
    if '--remove' in argv:
        print('已删除' if remove(root) else '没有装过')
        return 0
    print('写入', install(root))
    print(f'离线任务列表第 {ITEM} 项「潜艇母舰‧保卫作战」（{MISSION}）现在是潜舰对战母舰。')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
